### ISSUE TITLE
Does not show a large image

### ISSUE THREAD

**Issue by freimaks** [pexea12/vue-image-lightbox#10]
I have bug after update 5.3.0:

![image 4](https://user-images.githubusercontent.com/26241659/26890001-af386ef8-4bb8-11e7-9692-b8ed53b3edaa.png)

Why script.js has "require('./style.css')"?
![image 5](https://user-images.githubusercontent.com/26241659/26890079-040e514a-4bb9-11e7-81c9-b8efb0faff06.png)

**Comment by pexea12** [comment]
Your first picture seems quite vague to me because the images look like corrupted. My guess is that you didn't include the `vue-image-lightbox.min.css` file as requirement.

The `script.js` has `require('./style.css')` because this css file is needed for the lightbox style. When building for production, I have already built a min css file in `dist` folder. Therefore, you only need to include this `vue-image-lightbox.min.css`.

**Comment by freimaks** [comment]
@pexea12 But version 5.2.0 work in my project without this problem.

![image](https://user-images.githubusercontent.com/26241659/26898725-9da01750-4bd5-11e7-9a34-7f4868f1c70a.png)

**Comment by pexea12** [comment]
![image](https://user-images.githubusercontent.com/10600525/26910154-4849a24e-4c2f-11e7-9a67-669b5176f31c.png)

Things are fine with me. You should provide more information about the bug. 
Were there any logs? Was the image loaded succesfully but not displayed correctly?
When you move to other images, can they be displayed correctly?

**Comment by freimaks** [comment]
I found the error.

![image](https://user-images.githubusercontent.com/26241659/26947374-31815f22-4c9b-11e7-9e4a-a80a886a825a.png)

In .js:
`"img",{key:t.imagesSrc[t.select].src,staticClass:"vue-lb-modal-image",attrs:{src:t.imagesSrc[t.select].src}})]`

Instead of **imagesSrc[t.select].src** there should be **images[t.select].src**

**Comment by pexea12** [comment]
I fixed it in [5.4.1](https://github.com/pexea12/vue-image-lightbox/releases/tag/5.4.1). Please read the changelog carefully.
