### ISSUE TITLE
Swipe actions don't initialize when media is initially empty

### ISSUE THREAD

**Issue by Acolloyds** [pexea12/vue-image-lightbox#105]
When the `media` prop has an empty array initially, the `container` element doesn't render, so the value of `this.$refs.container` is null. 

The HammerJS swipe actions get initialized in the `mounted` method, but if the media array is empty, they never get initialized.

Solutions:
Either keep the container div rendered even if media is empty.
Or move initialization to a watcher so that it gets reinitialized every time the container is rendered.

**Comment by janosrusiczki** [comment]
This is a very good catch, on my fork I spent quite a while figuring it out. My solution (in my use case) was that since the lightbox is hidden when it is initialized I would pass something like `['dummy']` to the media array and this way the watchers get initialized and then before showing the lightbox I'm filling the array with real media.

From your proposed solution I would go with the second one. Seems more robust.
