### ISSUE TITLE
Demo with showLightBox= false option is giving "Uncaught TypeError: Cannot set property 'showLightBox' of undefined"

### ISSUE THREAD

**Issue by flakobatako** [pexea12/vue-image-lightbox#28]
If i try the demo everything works as expected, but if i try to use the option showLightBox= false, whenever i click a thumbnail i'm getting the message: "Uncaught TypeError: Cannot set property 'showLightBox' of undefined".

**Comment by covertbert** [comment]
In case you're still stuck on this or anyone else comes here in the future... I got this error too and it's because you have to specify and `ref` of `lightbox` when you render the component.

e.g: `lightbox(:images="images", :showLightBox="false", :autoPlay="true", :startAt="startIndex", ref="lightbox")`

By doing this you can call `this.$refs.lightbox.showImage(index)` and `this.$refs` won't be undefined.
