### ISSUE TITLE
Mem leak

### ISSUE THREAD

**Issue by imcvampire** [pexea12/vue-image-lightbox#42]
You must destroy `hammer` created in `mounted` hook in `beforeDestroy` hook

**Comment by pexea12** [comment]
Hammer is not a traditional event emitter from javascript. It is only a normal object which follows observer pattern. Therefore, there is no need to destroy it because Javascript garbage collection will do it for us.

**Comment by imcvampire** [comment]
No, you still have to stop, destroy and set this variable to null to get garbage collector work.
You can check its documentation (http://hammerjs.github.io/api/) and an example from a react component (https://github.com/JedWatson/react-hammerjs/blob/master/src/Hammer.js#L122)

**Comment by pexea12** [comment]
You are right in case of a dangling pointer where you attach an event to an outside component.

 For example, if you attach event `e` to component `Father` which uses component `Child`. If `Child` is destroyed but `Father` and `e` are alive, then there will be a problem. Therefore, `e` must be detached and destroyed also. However, if `Child` and `Father` are destroyed, there will be no dangling references and garbage collector can work well without killing `e`.

You should notice that I attach 2 `hammer` event to a DOM component which is inside the lightbox. After the lightbox is destroyed, both the `hammer` object and this DOM component are destroyed also. Therefore it is unnecessary to detach and destroy the attached event.

In the React component `vue-hammer` above, you can see that the `hammer` object is a property of the component (`this.hammer`). Hence, when the component is unmounted, he must kill the event because the DOM component is destroyed but the `hammer` is still alive. Things are different in the lightbox because `hammer` is destroyed even before the DOM component is destroyed. I used to consider detach it but I found it unnecessary.

**Comment by imcvampire** [comment]
Thank you, I get your point! But I will do more test to make sure everything works properly!
