### ISSUE TITLE
Nuxt Page refresh

### ISSUE THREAD

**Issue by riveraeu** [pexea12/vue-image-lightbox#56]
Hey I really like this component, but am running into some issues with refreshing the page in my Nuxt app.

![image](https://user-images.githubusercontent.com/9275810/51716011-eddf7400-1fef-11e9-8f30-b9f77955a756.png)

Here are my dependencies:
`"nuxt": "^2.0.0",`
`"vue-image-lightbox": "^6.0.1",`
`"vue-lazyload": "^1.2.6",`
`"vue-touch": "^1.1.0",`

and here is the page using the lightbox component 

![image](https://user-images.githubusercontent.com/9275810/51716125-65150800-1ff0-11e9-8dc4-9ba874cca4be.png)

I have set up Lazyload as a Nuxt plugin like this

plugins/lazyLoad.js:
`import Vue from 'vue'`
`import VueLazyLoad from 'vue-lazyload'`

`Vue.use(VueLazyLoad)`

nuxt.config.js:
`'@/plugins/lazyLoad`

What ive tried: 

- ssr false for plugin `{ src: '@/plugins/lazyLoad', ssr: false }`
- `<no-ssr>` tags wrapped around `<Lightbox>`
- tested on netlify server as a static generated site
- [https://github.com/pexea12/vue-image-lightbox/issues/31](url)

Any help would be greatly appreciated, thanks!

**Comment by pexea12** [comment]
I am investigating it

**Comment by pexea12** [comment]
The new version [6.1.1](https://github.com/pexea12/vue-image-lightbox/releases/tag/6.1.1) is now SSR-supported.

However, it seems to be a Nuxt.js problem since I am unable to fix this error. When I copied the LightBox to `components` folder of Nuxt, everything is fine but importing `vue-image-lightbox` from `node_modules` gave this error. 
I think the best work-around now is copying LightBox to `components` folder.

**Comment by riveraeu** [comment]
Thanks for looking into this and for the workaround, the page is now refreshing without any errors!
